name: "Check with Bulloak that Solidity tests conform to BTT spec"

on:
  workflow_call:
    inputs:
      skip-modifiers:
        default: true
        required: false
        type: "boolean"

      tree-path:
        default: "test/**/**.tree"
        required: false
        type: "string"

jobs:
  bulloak-check:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install and run Bulloak"
        uses: "smol-ninja/bulloak-toolchain@v1"
        with:
          skip-modifiers: ${{ inputs.skip-modifiers }}
          tree-path: ${{ inputs.tree-path }}

      - name: "Bulloak summary"
        run: |
          echo "## Bulloak result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Passed" >> $GITHUB_STEP_SUMMARY
