name: "Full check a project"

on:
  workflow_call:
    inputs:
      command:
        default: "full-check"
        description: 'The lint command to run (default: "full-check)"'
        required: false
        type: string
      command_runner:
        default: "just"
        description: 'The command runner to use (default: "just")'
        required: false
        type: string
      install_foundry:
        default: true
        description: "Whether to install Foundry (default: true)"
        required: false
        type: boolean
jobs:
  evm-lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Foundry"
        if: ${{ inputs.install_foundry }}
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Just"
        uses: "extractions/setup-just@v3"
        with:
          just-version: "1"

      - name: "Install Bun"
        uses: "oven-sh/setup-bun@v2"
        with:
          bun-version: "latest"

      - name: "Install the Node.js dependencies"
        run: "bun install --frozen-lockfile"

      - name: "Full check the code"
        run: "${{ inputs.command_runner }} ${{ inputs.command }}" # Runs Biome, Forge, Prettier, Solhint, etc.

      - name: "Add summary"
        run: | # shell
          echo "## Full Check result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Passed" >> $GITHUB_STEP_SUMMARY
